#define MICROPY_HW_BOARD_NAME               "LOLIN D32 PRO"
#define MICROPY_HW_MCU_NAME                 "ESP32"

#define MICROPY_HW_I2C0_SCL (22)
#define MICROPY_HW_I2C0_SDA (21)

#define MICROPY_HW_SPI1_SCK (18)
#define MICROPY_HW_SPI1_MOSI (23)
#define MICROPY_HW_SPI1_MISO (19)
